
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A107','45','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A108','45','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A109','45','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('CARBON','40','LABORATORIO DE CARBON','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A1','30','AULA KIOSKO','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A2','30','AULA','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A102','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('SP','35','SALA DE PROYECCIONES','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('SD','30','SALON DE DIBUJOS','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('S1','36','SALA DE INFORMATICA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('S2','32','SALA DE INFORMATICA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A106','40','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A105','40','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A104','40','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A103','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('ED','20','LABORATORIO DE CONTABILIDAD','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('L1','30','LABORATORIO DE ELECTRICIDAD','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('L2','30','LABORATORIO QUIMICA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LAP','30','LABORATORIO APRISCO','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LPO','30','PORQUERIZA','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LES','30','ESTANQUE PISCICOLA','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LGA','30','GALPON','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LCU','30','LABORATORIO CULTIVO','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LLO','30','LABORATORIO LOMBRICULTURA','ACTIVO','10','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('B1','96','BIBLIOTECA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A110','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A111','45','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A112','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('1','45','SALA INFORMÁTICA NUEVA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A113','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A101','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LC','45','LC','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('LI','45','LI','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('01','45','INFORMATICA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('02','45','INFORMATICA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('03','45','INFORMATICA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('CD','200','CAMPO DEPORTIVO','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('AULA DISTRA','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('AJUNTA','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A116','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A114','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A118','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A121','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A123','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A125','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A127','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A129','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A115','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A117','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A120','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A122','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A119','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A124','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A126','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A128','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('A130','50','AULA','ACTIVO','8','FISICO');
Insert into recursogenerals(nomenclatura,capacidad,descripcion,estado,espaciofisicor_id,tipo) values ('AULA SABER PRO','50','AULA SABER PRO','ACTIVO','8','FISICO');
